// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ed25519} from '../models';

export function CheckFileOnBlockchain(arg1:string):Promise<Array<main.BlockchainProofInfo>>;

export function ClearKey():Promise<void>;

export function GenerateAndSaveKey(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetCurrentKeyInfo():Promise<string|boolean>;

export function GetEthAddress():Promise<string>;

export function RegisterFileOnChain(arg1:string):Promise<string>;

export function RemoveSignatureAction(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectSaveFile(arg1:string):Promise<string>;

export function SignFileAction(arg1:string,arg2:string,arg3:number):Promise<void>;

export function UnlockKey(arg1:string,arg2:string):Promise<string>;

export function VerifyFileAction(arg1:string,arg2:string):Promise<Array<ed25519.VerificationResult>>;
