// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileOnBlockchain(arg1) {
  return window['go']['main']['App']['CheckFileOnBlockchain'](arg1);
}

export function ClearKey() {
  return window['go']['main']['App']['ClearKey']();
}

export function GenerateAndSaveKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateAndSaveKey'](arg1, arg2, arg3);
}

export function GetCurrentKeyInfo() {
  return window['go']['main']['App']['GetCurrentKeyInfo']();
}

export function GetEthAddress() {
  return window['go']['main']['App']['GetEthAddress']();
}

export function RegisterFileOnChain(arg1) {
  return window['go']['main']['App']['RegisterFileOnChain'](arg1);
}

export function RemoveSignatureAction(arg1) {
  return window['go']['main']['App']['RemoveSignatureAction'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSaveFile(arg1) {
  return window['go']['main']['App']['SelectSaveFile'](arg1);
}

export function SignFileAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['SignFileAction'](arg1, arg2, arg3);
}

export function UnlockKey(arg1, arg2) {
  return window['go']['main']['App']['UnlockKey'](arg1, arg2);
}

export function VerifyFileAction(arg1, arg2) {
  return window['go']['main']['App']['VerifyFileAction'](arg1, arg2);
}
